# Generated by Django 4.0.10 on 2024-02-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyposition',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyposition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='member_no',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='office_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='sub_department',
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('super', 'Site Manager'), ('customer', 'Customer Company')], default='customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyDepartment',
        ),
        migrations.DeleteModel(
            name='CompanyPosition',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.role'),
        ),
    ]
