# Generated by Django 4.0.10 on 2024-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_role_remove_companydepartment_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'メール', 'verbose_name_plural': 'メール管理'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '権限', 'verbose_name_plural': '権限管理'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー管理'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'ユーザー情報', 'verbose_name_plural': 'ユーザー情報管理'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='label',
        ),
        migrations.AddField(
            model_name='role',
            name='role_id',
            field=models.CharField(default='member', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
