# Generated by Django 4.0.10 on 2024-03-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_alter_email_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
