# Generated by Django 4.0.10 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentfile',
            name='file',
            field=models.FileField(upload_to='media/attachments/'),
        ),
    ]
