# Generated by Django 4.0.10 on 2024-03-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
