# Generated by Django 4.0.10 on 2024-02-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0002_alter_attachmentfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentfile',
            name='file',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
