# Generated by Django 4.0.10 on 2024-03-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0003_customer_last_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
