# Generated by Django 4.0.10 on 2024-02-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0003_alter_attachmentfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachmentfile',
            options={'verbose_name': '添付ファイル', 'verbose_name_plural': '添付ファイル管理'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '顧客', 'verbose_name_plural': '顧客管理'},
        ),
        migrations.AlterModelOptions(
            name='customermemo',
            options={'verbose_name': '顧客メモ', 'verbose_name_plural': '顧客メモ管理'},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'メール', 'verbose_name_plural': 'メール管理'},
        ),
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'verbose_name': 'メールテンプレート', 'verbose_name_plural': 'メールテンプレート管理'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': '属性', 'verbose_name_plural': '属性管理'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'ステータス', 'verbose_name_plural': 'ステータス管理'},
        ),
    ]
