# Generated by Django 4.0.10 on 2024-02-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0004_alter_attachmentfile_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='to',
        ),
    ]
