# Generated by Django 4.0.10 on 2024-03-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0005_maildomain_mail_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='domain',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
