# Generated by Django 4.0.10 on 2024-03-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0005_remove_mail_bcc_remove_mail_cc_remove_mail_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
