# Generated by Django 4.0.10 on 2024-03-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0006_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermemo',
            old_name='memo',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='customermemo',
            name='memo_date',
        ),
    ]
