# Generated by Django 4.0.10 on 2024-03-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0006_alter_mail_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
