# Generated by Django 4.0.10 on 2024-03-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0007_maildomain_imap_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maildomain',
            old_name='box',
            new_name='mailbox',
        ),
    ]
