# Generated by Django 4.0.10 on 2024-03-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0008_rename_box_maildomain_mailbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IMAP',
                'verbose_name_plural': 'IMAP管理',
            },
        ),
    ]
